# Generated by Django 3.2 on 2022-10-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carcolor',
            options={'ordering': ('name',), 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.RenameField(
            model_name='carcolor',
            old_name='color',
            new_name='name',
        ),
    ]
