# Generated by Django 3.2 on 2022-10-14 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_auto_20221014_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carcolor', verbose_name='Цвет')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel', verbose_name='Модель авто')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-id',),
            },
        ),
    ]
